name: child workflow
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      project:
          type: string
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}  
    steps:
      - name: Step 1 child workflow
        run: |
          echo 'environment' ${{ inputs.environment }}  
          echo ${{ secrets.TEST_SECRET }} | sed 's/./& /g'
          echo github eventname- ${{ github.event_name }}
          echo github project- ${{ inputs.project }}    
