name: child workflow
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

  
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}  
    steps:
      - name: Step 1 child workflow
        run: echo ${{ secrets.TEST_SECRET }}
    
