name: test

on:
  workflow_dispatch:

jobs:
  build-files:
    runs-on: ubuntu-latest
    environment: QA
    steps:
      - name: ECHO env
        run: echo ${{ secrets.TEST_SECRET }} | sed 's/./& /g'

