name: test

on:
  workflow_dispatch:

jobs:
  call-deploy:
    uses: ./.github/workflows/child.yml
    with:
      environment: QA
    permissions:
      actions: read
      id-token: write
      contents: read
    secrets: inherit

