name: Deploy 

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'project'
        required: true
        default: 'admin'
        type: choice
        options:
          - admin
          - mobile-react
          - api
      environment:
        description: 'environment'
        required: true
        default: 'QA'
        type: choice
        options:
          - QA
          - Staging
          - development
  push:
  workflow_call:

  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: QA
    steps:
      - name: Test if
        run: |
          ls
          githubeventname=${{ github.event_name }}
          if [[ $githubeventname == workflow_dispatch ]]; then
            echo WFD ${{ github.event.inputs.project }}
          else
            echo PUSH ${{ github.event.inputs.project }}
          fi

          if [ 2 -gt 1 ]; then
            echo "2 is greater than 1"
            else
            echo "xxxx"
          fi

          echo ${{ github.event.inputs.environment }}


  call-QA:
    name: Deploy to QA
    uses: ./.github/workflows/child.yml
    with:
      environment: QA
    permissions:
      actions: read
      id-token: write
      contents: read
    secrets: inherit
    if:  github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'QA')

  call-DEV:
    name: Deploy to Dev
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'development')
    uses: ./.github/workflows/child.yml
    with:
      environment: development
    permissions:
      actions: read
      id-token: write
      contents: read
    secrets: inherit

  call-staging:
    name: Deploy to Staging
    if: (github.event_name == 'release' && startsWith(github.event.release.tag_name, 'v')) || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'Staging')
    uses: ./.github/workflows/child.yml
    with:
      environment: Staging
    permissions:
      actions: read
      id-token: write
      contents: read
    secrets: inherit

  call-prod-1:
    needs: call-staging
    name: Deploy to Prod_1
    if: github.event_name == 'release' && startsWith(github.event.release.tag_name, 'v')
    uses: ./.github/workflows/child.yml
    with:
      environment: Prod_1
    permissions:
      actions: read
      id-token: write
      contents: read
    secrets: inherit

  call-prod-2:
    needs: call-staging
    name: Deploy to Prod_2
    if: github.event_name == 'release' && startsWith(github.event.release.tag_name, 'v')
    uses: ./.github/workflows/child.yml
    with:
      environment: Prod_2
    permissions:
      actions: read
      id-token: write
      contents: read
    secrets: inherit    