name: test

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'project'
        required: true
        default: 'admin'
        type: choice
        options:
          - admin
          - mobile-react
          - api
      environment:
        description: 'environment'
        required: true
        default: 'QA'
        type: choice
        options:
          - QA
          - Staging
  workflow_call:

  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment == 'Staging' && 'Staging' || 'QA' }}
    steps:
      - name: Test if
        run: |
          ls
          githubeventname=${{ github.event_name }}
          if [[ $githubeventname == workflow_dispatch ]]; then
            echo WFD ${{ github.event.inputs.project }}
          else
            echo PUSH ${{ github.event.inputs.project }}
          fi

          if [ 2 -gt 1 ]; then
            echo "2 is greater than 1"
            else
            echo "xxxx"
          fi

          echo ${{ github.event.inputs.environment }}


  call-QA:
    uses: ./.github/workflows/child.yml
    with:
      environment: ${{ github.event.inputs.environment == 'Staging' && 'development' || 'QA' }}
    permissions:
      actions: read
      id-token: write
      contents: read
    secrets: inherit
    

  call-DEV:
    if: github.event.inputs.environment == 'development'
    uses: ./.github/workflows/child.yml
    with:
      environment: development
    permissions:
      actions: read
      id-token: write
      contents: read
    secrets: inherit

  DeployToStaging:
    name: Deploy to Staging
    if: github.event_name == 'release' && startsWith(github.event.release.tag_name, 'v')
    uses: ./.github/workflows/child.yml
    with:
      environment: Staging
    permissions:
      actions: read
      id-token: write
      contents: read
    secrets: inherit