name: test

on:
  workflow_dispatch:

jobs:
  call-QA:
    uses: ./.github/workflows/child.yml
    with:
      environment: QA
    permissions:
      actions: read
      id-token: write
      contents: read
    secrets: inherit

  call-DEV:
    uses: ./.github/workflows/child.yml
    with:
      environment: development
    permissions:
      actions: read
      id-token: write
      contents: read
    secrets: inherit

