name: test

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'project'
        required: true
        default: 'admin'
        type: choice
        options:
          - admin
          - mobile-react
          - api
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test if
        run: echo "building" ${{ github.event.inputs.project }} ${{ github.event.inputs.project }}
    if: ${{ github.event.inputs.project == 'admin' }} || ${{ github.event.inputs.project == 'api' }}

  call-QA:
    uses: ./.github/workflows/child.yml
    with:
      environment: QA
    permissions:
      actions: read
      id-token: write
      contents: read
    secrets: inherit
    

  call-DEV:
    uses: ./.github/workflows/child.yml
    with:
      environment: development
    permissions:
      actions: read
      id-token: write
      contents: read
    secrets: inherit

