name: test

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'project'
        required: true
        default: 'admin'
        type: choice
        options:
          - admin
          - mobile-react
          - api
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test if
        run: |
          ls
          echo ${{ github.ref }}
          ref='refs/tags/v'
          if [[ ${{ github.event_name == 'workflow_dispatch' }} ]]; then
            echo "WFLOW DISPATCH"
          else
            echo "NOT WORKFLOW"
          fi


  call-QA:
    uses: ./.github/workflows/child.yml
    with:
      environment: QA
    permissions:
      actions: read
      id-token: write
      contents: read
    secrets: inherit
    

  call-DEV:
    uses: ./.github/workflows/child.yml
    with:
      environment: development
    permissions:
      actions: read
      id-token: write
      contents: read
    secrets: inherit

